name: Flutter CI

# Trigger on pushes to any branch and on tag pushes
on:
  push:
    branches: [main, master, develop]
  create:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - run: flutter pub get

      - run: dart format --set-exit-if-changed .

      - run: flutter analyze .

      # - run: flutter test

      - run: flutter build apk --release

      # Upload APK as artifact for all builds
      - uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      # Generate release date
      - name: Get current date
        if: startsWith(github.ref, 'refs/tags/')
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      # Create GitHub Release only when a tag is pushed
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
          name: Release quran app ${{ steps.date.outputs.date }}
          body: |
            ## What's Changed
            - Updating the UI
            - Adding tafsir

            ## Running The APP
            - **Android APK**: Download and install the `app-release.apk` file below

            ---
            *This release was automatically generated by GitHub Actions*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
